### ISSUE TITLE
log_dict() got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by FluidSense** [PyTorchLightning/metrics#199]
## 🐛 Bug

The docs of [`MetricCollection`](https://torchmetrics.readthedocs.io/en/v0.2.0/pages/overview.html#metriccollection) uses `self.log_dict` to log all of the metrics in the collection. To add a prefix to the logged values, the `prefix` keyword argument is set. However, I cannot seem to find this argument [implemented anywhere in the LightningModule of PytorchLightning.](https://github.com/PyTorchLightning/pytorch-lightning/blob/master/pytorch_lightning/core/lightning.py#L331)

Have I misunderstood which `log_dict` is in use or are the docs wrong?

### To Reproduce

1. Create a `BoringModel` with a `MetricCollection`
2. Try to call `self.log_dict(..., prefix="something")`
3. See error

![image](https://user-images.githubusercontent.com/22146437/115956074-11f5cc80-a4fb-11eb-97ef-3247b52e60c2.png)

### Environment

 - PyTorch Version (e.g., 1.0): Pytorch Lighting v. 1.2.10
 - OS (e.g., Linux): Linux (WSL2/Ubuntu)
 - How you installed PyTorch (`conda`, `pip`, source): poetry
 - Build command you used (if compiling from source):
 - Python version: 3.8.5
 - CUDA/cuDNN version:
 - GPU models and configuration:
 - Any other relevant information:

**Comment by SkafteNicki** [comment]
Hi @FluidSense,
The documentation is wrong for v0.2. It was determined that the `prefix` arg was better suited to have directly in the `MetricCollection` class ``__init__`` method. This have already been fixed in the documentation, please see either `stable` or `latest` docs: https://torchmetrics.readthedocs.io/en/latest/pages/overview.html#metriccollection
