### ISSUE TITLE
implement own BERT score

### ISSUE THREAD

**Issue by Borda** [PyTorchLightning/metrics#432]
## 🚀 Feature

we shall come with our own BERT implementation as the bert_score require heavy Transformers dependency
follow-up for #424

### Motivation

keep the TM dependency light, and use other packages only as a reference

### Alternatives

use another package that has less dependencies and still use this one as reference

**Comment by stancld** [comment]
@Borda  - Would it be a possible workaround to write the own BERTScore implementation (as in the case of rouge and other text metrics) and ask a user to pass in its model, dataloader/s and a forward method (similarly to the PL) to compute embeddings? In this way, it would give a user the freedom to use whichever implementation of a transformer model (not necessary the huggingface `transformers`). At the same time, it would remove the `transformers`' dependency. 

In any case, I think it would be also necessary to write own BERT/Transformer implementation in order to provide a user with the feature of a baseline rescaling as suggested in the original paper.

For me, one blocker is that I'm not sure how can be implemented the argument `num_layers` to subsample only some of the transformer layers (as it is the case in the current implementation of BERTScore) because of potentially varying models' implementation. Though, I believe there's a reasonable solution...

If this sounds good to you, I'd be happy to start working on a draft PR :)

**Comment by Borda** [comment]
> In this way, it would give a user the freedom to use whichever implementation of a transformer model

that would be great!, we could just keep an example with HF if a user does wants to use something prepared

> I think it would be also necessary to write own BERT/Transformer implementation

not sure if Metrics shall hold implementation of "any" model, in my eyes it shall be model agnostic, but happy to hear other opinions?

> I'm not sure how can be implemented the argument `num_layers`

I think this is widely link to the model used, so it shall be passed with the model, eventually, we can think about some wrapper which would expose just some portion of a model (if it a standard model)

@PyTorchLightning/core-metrics @SkafteNicki

**Comment by SkafteNicki** [comment]
It would be great to have this being model agnostic. IMO it would still be great if `BERTScore` had like a base feature extractor being the one commonly used. Not sure what to do with the importing of this other than if user request the default extractor we can kindly ask them to install the HF Transformer.

**Comment by Borda** [comment]
@stancld interested in sending a PR? then we can make quick `v0.5.1` :rabbit:

**Comment by stancld** [comment]
@Borda - Great, I'll start working on it this afternoon 🙂

**Comment by Borda** [comment]
@stancld how is it going here? do you think we can address also #472

**Comment by stancld** [comment]
> @stancld how is it going here? do you think we can address also #472

@Borda - I'll open a draft PR tonight. The PR definitely still requires some work, but I've already had something.

#472 Seems to me this is a consequence of storing references and predictions in a form of `List[str]`. I will take a look at that!

**Comment by stancld** [comment]
Hello @Borda, just a quick update regarding PR #473. I think that almost most of the features, tests and an example with a user's own model have been already implemented. I yet need to finish some docs to helper functions and go through the code once or twice again as it's a quite large PR.

**Comment by ankitar** [comment]
@stancld do share the draft pr whenever ready!

**Comment by stancld** [comment]
Hey @ankitar, please feel free to look at #473, it's almost ready for some initial review.

**Comment by ankitar** [comment]
@stancld Do test for the following issue too, https://github.com/PyTorchLightning/metrics/issues/472

**Comment by stancld** [comment]
@ankitar Should've already been there :)
