### ISSUE TITLE
Allow automatically adjusting `k` for `RetrievalPrecision` when `k > num(retrieved documents)`

### ISSUE THREAD

**Issue by stancld** [PyTorchLightning/metrics#886]
## 🚀 Feature

Allow `RetrievalPrecision` to use `k=min(k, preds.shape[-1])` for individual queries.

### Motivation

When one calculates `precision at k` for a query over the list of documents `D`, where `len(D) < k`, there's an ambiguity whether `k` should be fixed or adjusted w.r.t. `len(D)` when `D < k`.

### Pitch

Add an input argument for an option of how to handle these edge cases. Set a default to match the current implementation.

### Alternatives

Leave it as it is.

### Additional context

The implementation described above is used by the [`catboost` package](https://github.com/catboost/catboost).

**Comment by lucadiliello** [comment]
It makes sense for me. Actually someone may want to use it because, at the moment, if you have `k` greater than the number of documents you cannot get `1` on that query even if your system is perfect.

I can implement it if you want. I would add a `adaptive_k` boolean parameter. Do you suggest other names?

**Comment by SkafteNicki** [comment]
`adaptive_k` is fine by me :]

**Comment by lucadiliello** [comment]
I will add this argument to all the retrieval metrics which have `k` as parameter ok?

**Comment by SkafteNicki** [comment]
@lucadiliello sounds good to me :]
